[project]
name = "leapfrog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<=3.10.16"
dependencies = [
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "numpy>=2.0.2",
    "pillow>=11.1.0",
    "tensorflow>=2.19.0",
]
